# Generated by Django 3.2.12 on 2022-04-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_librarian',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Librarian'),
        ),
    ]
